---
# Tasks for nginx

- name: Add nginx ppa
  apt_repository: repo=ppa:nginx/stable state=present

- name: Install web server packages
  apt: pkg=$item state=installed
  with_items:
    - nginx

- name: Remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure log directory exists
  file: dest=/var/log/{{ app_name }} state=directory

- name: Copy over nginx.conf file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create nginx site config
  template: src=nginx_site.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }}.conf

- name: Link nginx config to sites-enabled
  file: src=/etc/nginx/sites-available/{{ app_name }}.conf dest=/etc/nginx/sites-enabled/{{ app_name }}.conf state=link
  notify:
    - restart nginx
